### PR TITLE
Add terminal application for Sitara devices

### PR DESCRIPTION
**Pull request by paresh-bhagat12**
This commit adds terminal application based on qmlterwidget in ti-apps-launcher.

### CODE REVIEW

**Comment by cshilwant** [comment]
@paresh-bhagat12 Can you validate the changes on AM62SIP as it runs on eglfs by default (instead of wayland) - https://github.com/TexasInstruments/meta-tisdk/blob/scarthgap/recipes-demos/ti-apps-launcher/ti-apps-launcher/ti-apps-launcher-eglfs.service

**Comment by paresh-bhagat12** [comment]
@cshilwant i have verified it on am62sip

**Review by jsuhaas22 — APPROVED** [review]
LGTM

**Review by cshilwant — APPROVED** [review]
LGTM

**Pull request merged**
